import { FormSection } from './types';

export const formStructure: FormSection[] = [
    {
        title: 'Demographics',
        fields: [
            { id: 'centerId', label: 'Center ID', type: 'number', required: false },
            { id: 'serialNumber', label: 'Serial Number/Institutional Code', type: 'text', required: true },
            { id: 'age', label: 'Age (years)', type: 'number', required: true },
            { id: 'hospitalName', label: 'Hospital Name', type: 'text', required: true },
            { id: 'hospitalLocation', label: 'Location of Hospital (State)', type: 'text', required: true },
            { id: 'geographicalZone', label: 'Geographical Zone', type: 'text', required: true },
            { id: 'sex', label: 'Sex', type: 'radio', options: ['Male', 'Female'], required: true },
            { id: 'occupation', label: 'Occupation', type: 'radio', options: ['Civil servant', 'Professional', 'Trading', 'Farming', 'Retiree', 'Others'], required: true },
            { id: 'occupationOther', label: 'If Others, specify occupation', type: 'text', condition: (data) => data.occupation === 'Others' },
            { id: 'educationLevel', label: 'Education Level', type: 'radio', options: ['Nil', 'Primary', 'Secondary', 'Tertiary', 'Other'], required: true },
            { id: 'educationLevelOther', label: 'If Other, specify education level', type: 'text', condition: (data) => data.educationLevel === 'Other' },
            { id: 'residentialArea', label: 'Residential Area', type: 'radio', options: ['Urban', 'Semi-urban', 'Rural'], required: true },
        ],
    },
    {
        title: 'Diabetes',
        fields: [
            { id: 'diabetesType', label: 'Type of diabetes', type: 'radio', options: ['Type 1', 'Type 2', 'Other'], required: true },
            { id: 'diabetesTypeOther', label: 'If Other, specify type', type: 'text', condition: (data) => data.diabetesType === 'Other' },
            { id: 'previousDiagnosis', label: 'Previous diagnosis of diabetes', type: 'radio', options: ['Yes', 'No'], required: true },
            { id: 'durationOfDiabetes', label: 'If Yes, duration of diabetes (years)', type: 'number', condition: (data) => data.previousDiagnosis === 'Yes' },
            { id: 'currentMedications', label: 'Current medications', type: 'checkbox', options: ['Oral hypoglycemics', 'Insulin', 'Others'], required: true },
            { id: 'medicationOther', label: 'If Others medication, specify', type: 'text', condition: (data) => data.currentMedications?.includes('Others') },
            { id: 'oralHypoglycemicAgents', label: 'Oral hypoglycemic agents', type: 'checkbox', options: ['Sulfonylureas', 'TZD', 'Metformin', 'SGLUT2', 'Other', 'None'], required: true },
            { id: 'oralHypoglycemicAgentsOther', label: 'If Other oral hypoglycemic agents, specify', type: 'text', condition: (data) => data.oralHypoglycemicAgents?.includes('Other') },
            { id: 'medicationAdherence', label: 'Adherence to medication', type: 'radio', options: ['Yes', 'No'], required: true },
            { id: 'previousAdmissions', label: 'Previous hospital admissions for diabetes-related complications', type: 'radio', options: ['Yes', 'No'], required: true },
            { id: 'previousAdmissionsCount', label: 'If Yes, how many times?', type: 'number', condition: (data) => data.previousAdmissions === 'Yes' },
            { id: 'lastAdmissionDate', label: 'How long ago was the last admission?', type: 'text', condition: (data) => data.previousAdmissions === 'Yes' },
            { id: 'hypertension', label: 'Hypertension', type: 'radio', options: ['Yes', 'No'], required: true, helpText: "Presence of comorbidities" },
            { id: 'ckd', label: 'CKD (Chronic Kidney Disease)', type: 'radio', options: ['Yes', 'No'], required: true },
            { id: 'previousStroke', label: 'Previous stroke', type: 'radio', options: ['Yes', 'No'], required: true },
            { id: 'heartFailure', label: 'Heart failure', type: 'radio', options: ['Yes', 'No'], required: true },
            { id: 'otherComorbidities', label: 'Other comorbidities (specify)', type: 'text' },
        ],
    },
    {
        title: 'Admission',
        fields: [
            { id: 'admissionDiagnosis', label: 'Admission diagnosis', type: 'checkbox', options: ['Infection', 'DKA', 'HHS', 'Cardiovascular event', 'Other'], required: true },
            { id: 'admissionDiagnosisOther', label: 'If Other, specify', type: 'text', condition: (data) => data.admissionDiagnosis?.includes('Other') },
            { id: 'bloodPressure', label: 'Blood Pressure (mmHg)', type: 'text', required: true, helpText: 'Vital signs at admission' },
            { id: 'pulseRate', label: 'Pulse rate (/min)', type: 'text', required: true },
            { id: 'temperature', label: 'Temperature (°C)', type: 'text', required: true },
            { id: 'respiratoryRate', label: 'Respiratory rate (/min)', type: 'text', required: true },
        ],
    },
    {
        title: 'Labs',
        fields: [
            { id: 'glucoseMeasurementMethod', label: 'How was the blood glucose measured?', type: 'radio', options: ['Glucometer', 'Laboratory', 'Both'], required: true },
            { id: 'bloodGlucoseAdmission', label: 'Blood glucose levels at admission (mg/dL or mmol/L)', type: 'text', required: true },
            { id: 'hba1c', label: 'HbA1c (%; if available)', type: 'text' },
            { id: 'wbc', label: 'WBC (total)', type: 'text', required: true, helpText: 'Complete blood count' },
            { id: 'neutrophil', label: 'Neutrophil (%)', type: 'text', required: true },
            { id: 'lymphocytes', label: 'Lymphocytes (%)', type: 'text', required: true },
            { id: 'pcv', label: 'PCV (%)', type: 'text', required: true },
            { id: 'bloodCulture', label: 'Blood culture', type: 'radio', options: ['Yes', 'No'], required: true },
            { id: 'bloodCultureOrganism', label: 'If Yes, isolated organism(s)', type: 'text', condition: (data) => data.bloodCulture === 'Yes' },
            { id: 'bloodCultureSensitivity', label: 'Antibiotic sensitivity', type: 'text', condition: (data) => data.bloodCulture === 'Yes' },
            { id: 'bloodCultureResistance', label: 'Antibiotic resistance', type: 'text', condition: (data) => data.bloodCulture === 'Yes' },
            { id: 'sputumCulture', label: 'Sputum culture (If available)', type: 'radio', options: ['Yes', 'No'], required: true },
            { id: 'sputumCultureOrganism', label: 'If Yes, isolated organism(s)', type: 'text', condition: (data) => data.sputumCulture === 'Yes' },
            { id: 'sputumSensitivity', label: 'Sputum antibiotic sensitivity', type: 'text', condition: (data) => data.sputumCulture === 'Yes' },
            { id: 'sputumResistance', label: 'Sputum antibiotic resistance', type: 'text', condition: (data) => data.sputumCulture === 'Yes' },
        ],
    },
    {
        title: 'Vitals',
        fields: [
            { id: 'ecgHeartRate', label: 'Heart Rate', type: 'text', required: true, helpText: "ECG" },
            { id: 'ecgLvh', label: 'LVH (Left Ventricular Hypertrophy)', type: 'radio', options: ['Yes', 'No'], required: true },
            { id: 'ecgAcuteMI', label: 'Features of Acute MI', type: 'radio', options: ['Yes', 'No'], required: true },
            { id: 'ecgAcuteMIFeatures', label: 'If Yes, list features', type: 'text', condition: (data) => data.ecgAcuteMI === 'Yes' },
            { id: 'renalCreatinine', label: 'Creatinine (micromol/L)', type: 'text', required: true, helpText: "Renal function tests" },
            { id: 'renalUrea', label: 'Urea (mg/dl)', type: 'text', required: true },
            { id: 'elSodium', label: 'Sodium', type: 'text', required: true, helpText: "Electrolyte levels" },
            { id: 'elPotassium', label: 'Potassium', type: 'text', required: true },
            { id: 'elHco3', label: 'HCO3', type: 'text', required: true },
            { id: 'elCl', label: 'Cl', type: 'text', required: true },
            { id: 'urineGlucose', label: 'Glucose in urine', type: 'radio', options: ['Yes', 'No'], required: true, helpText: "Urinalysis" },
            { id: 'urineKetone', label: 'Ketone in urine', type: 'radio', options: ['Yes', 'No'], required: true },
            { id: 'urineProtein', label: 'Protein in urine', type: 'radio', options: ['Yes', 'No'], required: true },
            { id: 'urineNitrites', label: 'Nitrites in urine', type: 'radio', options: ['Yes', 'No'], required: true },
            { id: 'urineCulture', label: 'Urine culture', type: 'radio', options: ['Yes', 'No'], required: true },
            { id: 'urineCultureOrganism', label: 'If Yes, isolated organism(s)', type: 'text', condition: (data) => data.urineCulture === 'Yes' },
            { id: 'urineSensitivity', label: 'Urine antibiotic sensitivity', type: 'text', condition: (data) => data.urineCulture === 'Yes' },
            { id: 'urineResistance', label: 'Urine antibiotic resistance', type: 'text', condition: (data) => data.urineCulture === 'Yes' },
            { id: 'lftAlt', label: 'ALT', type: 'radio', options: ['High', 'Normal', 'Low', 'Not Done'], required: true, helpText: "Liver function tests" },
            { id: 'lftAst', label: 'AST', type: 'radio', options: ['High', 'Normal', 'Low', 'Not Done'], required: true },
        ],
    },
    {
        title: 'Monitoring',
        description: 'Capillary Blood Glucose Readings (Day 1 to Day 14)',
        fields: [
            { id: 'glucoseMonitoring', label: 'Daily Glucose Readings', type: 'monitoring_table', required: true },
            { id: 'hypoglycemiaEpisodes', label: 'Episodes of hypoglycemia (<70 mg/dL)', type: 'radio', options: ['Yes', 'No'], required: true },
            { id: 'hypoglycemiaCount', label: 'Number of hypoglycemia episodes', type: 'number', condition: (data) => data.hypoglycemiaEpisodes === 'Yes' },
            { id: 'hyperglycemiaEpisodes', label: 'Episodes of hyperglycemia (>250 mg/dL)', type: 'radio', options: ['Yes', 'No'], required: true },
            { id: 'hyperglycemiaCount', label: 'Number of hyperglycemia episodes', type: 'number', condition: (data) => data.hypoglycemiaEpisodes === 'Yes' },
        ],
    },
    {
        title: 'Outcomes',
        fields: [
            { id: 'complicationInfections', label: 'Infections', type: 'checkbox', options: ['Sepsis', 'Pneumonia', 'Urinary tract infections', 'Other infections'], required: true, helpText: "New-onset Complications" },
            { id: 'complicationInfectionsOther', label: 'If Other infections, specify', type: 'text', condition: (data) => data.complicationInfections?.includes('Other infections') },
            { id: 'complicationAki', label: 'Acute kidney injury', type: 'radio', options: ['Yes', 'No'], required: true },
            { id: 'complicationCardio', label: 'Cardiovascular events', type: 'radio', options: ['Yes', 'No'], required: true },
            { id: 'complicationOther', label: 'Other complications (specify)', type: 'text' },
            { id: 'interventionInsulin', label: 'Insulin therapy', type: 'radio', options: ['Yes', 'No'], required: true, helpText: "Interventions" },
            { id: 'interventionInsulinDoses', label: 'Doses per day', type: 'number', condition: (data) => data.interventionInsulin === 'Yes' },
            { id: 'interventionInsulinTypes', label: 'Types of Insulin used', type: 'checkbox', options: ['Rapidly acting insulin', 'Soluble insulin', 'Others'], condition: (data) => data.interventionInsulin === 'Yes' },
            { id: 'interventionInsulinTypesOther', label: 'If Others, specify type', type: 'text', condition: (data) => data.interventionInsulin === 'Yes' && data.interventionInsulinTypes?.includes('Others') },
            { id: 'interventionInsulinAverageDose', label: 'Average dose of insulin used/day', type: 'text', condition: (data) => data.interventionInsulin === 'Yes' },
            { id: 'interventionInsulinMode', label: 'Mode of insulin administration', type: 'radio', options: ['Periodic administration', 'Intravenous insulin infusion', 'Others'], condition: (data) => data.interventionInsulin === 'Yes' },
            { id: 'interventionInsulinModeOther', label: 'If Others, specify mode', type: 'text', condition: (data) => data.interventionInsulin === 'Yes' && data.interventionInsulinMode === 'Others' },
            { id: 'interventionAntibiotic', label: 'Antibiotic therapy', type: 'radio', options: ['Yes', 'No'], required: true },
            { id: 'interventionFluid', label: 'Fluid management', type: 'radio', options: ['Yes', 'No'], required: true },
        ],
    },
    {
        title: 'Discharge',
        fields: [
            { id: 'dischargeStayLength', label: 'Length of hospital stay (days)', type: 'number', required: true, helpText: "Discharge Information" },
            { id: 'dischargeStatus', label: 'Discharge status', type: 'radio', options: ['Recovery', 'Transfer', 'Death'], required: true },
            { id: 'dischargeDiagnosis', label: 'Discharge diagnosis', type: 'text', required: true },
            { id: 'dischargeFollowUp', label: 'Follow-up recommendations', type: 'radio', options: ['Yes', 'No'], required: true },
            { id: 'dischargeCauseOfDeath', label: 'If death, cause of death', type: 'text', condition: (data) => data.dischargeStatus === 'Death' },
            { id: 'additionalTotalAdmitted', label: 'Total number of patients admitted into medical wards within the study period', type: 'number', required: true, helpText: "Additional Information" },
            { id: 'resourceEndocridologist', label: 'Endocridologist', type: 'radio', options: ['Yes', 'No'], required: true, helpText: "Resources Available in the Hospital" },
            { id: 'resourceRegistrar', label: 'Senior registrar in EDM', type: 'radio', options: ['Yes', 'No'], required: true },
            { id: 'resourceDiabeticNurse', label: 'Diabetic nurse', type: 'radio', options: ['Yes', 'No'], required: true },
            { id: 'resourceOrthoSurgeon', label: 'Orthopaedic surgeon', type: 'radio', options: ['Yes', 'No'], required: true },
            { id: 'resourcePlasticSurgeon', label: 'Plastic surgeon', type: 'radio', options: ['Yes', 'No'], required: true },
            { id: 'resourcePodiatrist', label: 'Podiatrist/orthotist', type: 'radio', options: ['Yes', 'No'], required: true },
            { id: 'resourceNutritionist', label: 'Nutritionist/dietician', type: 'radio', options: ['Yes', 'No'], required: true },
            { id: 'resourceInfusionPump', label: 'Infusion given pump', type: 'radio', options: ['Yes', 'No'], required: true },
            { id: 'resourceInsulinPump', label: 'Insulin infusion pump', type: 'radio', options: ['Yes', 'No'], required: true },
        ],
    },
    {
        title: 'Costs',
        fields: [
            { id: 'costPatientLocation', label: 'Where is the patient managed?', type: 'checkbox', options: ['Emergency Unit', 'General Ward', 'ICU/HDU', 'Isolation Ward'], required: true },
            { id: 'costBedDaysEU', label: 'Bed-days: Emergency Unit', type: 'number', required: true, helpText: "Put 0 if not applicable" },
            { id: 'costBedDaysGW', label: 'Bed-days: General Ward', type: 'number', required: true },
            { id: 'costBedDaysICU', label: 'Bed-days: ICU/HDU', type: 'number', required: true },
            { id: 'costBedDaysIW', label: 'Bed-days: Isolation Ward', type: 'number', required: true },
            { id: 'costDiagFBC', label: 'Diagnostics: FBC (quantity)', type: 'number', required: true },
            { id: 'costDiagUE', label: 'Diagnostics: U + E / Creatinine (quantity)', type: 'number', required: true },
            { id: 'costDiagLFTs', label: 'Diagnostics: LFTs (quantity)', type: 'number', required: true },
            { id: 'costDiagCRPESR', label: 'Diagnostics: CRP / ESR (quantity)', type: 'number', required: true },
            { id: 'costDiagGlucose', label: 'Diagnostics: Blood Glucose (quantity)', type: 'number', required: true },
            { id: 'costDiagBloodCulture', label: 'Diagnostics: Blood Culture (quantity)', type: 'number', required: true },
            { id: 'costDiagWoundCulture', label: 'Diagnostics: Wound Culture (quantity)', type: 'number', required: true },
            { id: 'costDiagABG', label: 'Diagnostics: Arterial Blood Gases (ABG) (quantity)', type: 'number', required: true },
            { id: 'costDiagHbA1c', label: 'Diagnostics: HbA1c (quantity)', type: 'number', required: true },
            { id: 'costDiagFLP', label: 'Diagnostics: FLP (quantity)', type: 'number', required: true },
            { id: 'costDiagOthers', label: 'Diagnostics: Others / Specify (quantity)', type: 'number', required: true },
            { id: 'costImagingCXR', label: 'Imaging: CXR (quantity)', type: 'number', required: true },
            { id: 'costImagingDoppler', label: 'Imaging: Doppler / Ultrasound (quantity)', type: 'number', required: true },
            { id: 'costImagingECG', label: 'Imaging: ECG (quantity)', type: 'number', required: true },
            { id: 'costImagingEcho', label: 'Imaging: Echocardiography (quantity)', type: 'number', required: true },
            { id: 'costImagingCTMRI', label: 'Imaging: CT / MRI (quantity)', type: 'number', required: true },
            { id: 'costImagingXray', label: 'Imaging: X-ray (quantity)', type: 'number', required: true },
            { id: 'costImagingOthers', label: 'Imaging: Others (Specify) (quantity)', type: 'number', required: true },
            { id: 'costProcABI', label: 'Procedures: ABI (quantity)', type: 'number', required: true },
            { id: 'costProcWound', label: 'Procedures: Wound swab / debridement (quantity)', type: 'number', required: true },
            { id: 'costProcSurgery', label: 'Procedures: Surgery (quantity)', type: 'number', required: true },
            { id: 'costMedsInsulin', label: 'Medicine: Insulin (types)', type: 'text', required: true },
            { id: 'costMedsOral', label: 'Medicine: Oral antidiabetic (if used)', type: 'text', required: true },
            { id: 'costMedsAntibiotics', label: 'Medicine: Antibiotics (agents / days)', type: 'text', required: true },
            { id: 'costMedsIV', label: 'Medicine: IV fluid', type: 'text', required: true },
            { id: 'costMedsAnticoagulants', label: 'Medicine: Anticoagulants', type: 'text', required: true },
            { id: 'costMedsAnalgesics', label: 'Medicine: Analgesics', type: 'text', required: true },
            { id: 'costMedsAntihypertensives', label: 'Medicine: Antihypertensives', type: 'text', required: true },
            { id: 'costMedsOthers', label: 'Medicine: Others (Specify)', type: 'text', required: true },
            { id: 'costConsumablesCatheter', label: 'Consumables: Catheter (quantity)', type: 'number', required: true },
            { id: 'costConsumablesCannulas', label: 'Consumables: Cannulas (quantity)', type: 'number', required: true },
            { id: 'costConsumablesDressing', label: 'Consumables: Dressing (quantity)', type: 'number', required: true },
            { id: 'costConsumablesStrips', label: 'Consumables: Glucose test strips (quantity)', type: 'number', required: true },
            { id: 'costConsumablesLancets', label: 'Consumables: Lancets (quantity)', type: 'number', required: true },
            { id: 'costConsumablesSyringes', label: 'Consumables: Syringes (quantity)', type: 'number', required: true },
            { id: 'costProfSpecialist', label: 'Professional Services: Specialist Consults', type: 'text', required: true },
            { id: 'costProfNursing', label: 'Professional Services: Nursing Procedures', type: 'text', required: true },
            { id: 'costProfPhysio', label: 'Professional Services: Physiotherapy fee', type: 'text', required: true },
            { id: 'costProfDietetics', label: 'Professional Services: Dietetics Consulting', type: 'text', required: true },
            { id: 'costHealthInsurance', label: 'Do you have health insurance?', type: 'radio', options: ['NHIA', 'State Scheme', 'Private', 'None'], required: true },
            { id: 'costNonMedIncome', label: 'Monthly personal income (Naira ₦)', type: 'number', required: true, helpText: "Non-medical costs during admission" },
            { id: 'costNonMedPatientTransport', label: 'Patient transport to hospital (Naira ₦)', type: 'number', required: true },
            { id: 'costNonMedCaregiverTransport', label: 'Caregiver transport (Naira ₦)', type: 'number', required: true },
            { id: 'costNonMedMeals', label: 'Cost of meals for patient (Naira ₦)', type: 'number', required: true },
            { id: 'costNonMedMisc', label: 'Miscellaneous (Naira ₦)', type: 'number', required: true },
        ],
    },
];
